name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare data
      run: |
        mkdir -p data
        python data_create.py

    - name: Save prepared data to artifacts
      run: |
        mkdir -p artifacts
        cp -r data artifacts/prepared_data

  train-models:
    runs-on: ubuntu-latest
    needs: prepare-data

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train models
      run: |
        mkdir -p models
        python train_model.py

    - name: Save trained models to artifacts
      run: |
        mkdir -p artifacts
        cp -r models artifacts/trained_models

  report-notebook:
    runs-on: ubuntu-latest
    needs: train-models

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt jupyter

    - name: Execute notebook
      run: |
        mkdir -p artifacts/reports
        jupyter nbconvert --to notebook --execute notebooks/analysis.ipynb --output artifacts/reports/analysis_executed.ipynb

    - name: Commit and push artifacts
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add artifacts/
        git commit -m "Add artifacts from CI/CD pipeline"
        git push origin main
